/**
 * Represents a user in the Treasury Management Dashboard system.
 *
 * Users have a starting balance of $1,000,000 and can perform transactions
 * such as buying/selling treasuries and funding/withdrawing from their account.
 *
 * @property {number} id - Unique identifier for the user (auto-generated by database)
 * @property {string} name - Display name of the user
 * @property {number} balance - Current account balance in USD (decimal number, e.g., 1000000.00)
 * @property {string} created_at - ISO 8601 timestamp of when the user account was created (e.g., "2025-01-15T10:30:00Z")
 */
export interface User {
  id: number;
  name: string;
  balance: number;
  created_at: string;
}
